name: buildAPK
on: push
  # push:
  #   branches-ignore: 
  #     - "release"
    
jobs: 
  Build:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message,'[build all]') || contains(github.event.head_commit.message,'[build apk]')}}

    steps:
      - name: üèó Setup repo
        uses: actions/checkout@v3

      - name: find files
        run: ls -la
        # run: grep -rl "${BASIC_HEADER_HASH}" .
        
      - name: Set environment variable
        run: echo "BASIC_HEADER_HASH=${{ secrets.BASIC_HEADER_HASH }}" >> $GITHUB_ENV
      
      - name: Replace occurrences
        # run: |
        #   for file in $(find . -type f -name '*.js' -o -name '*.tsx' -o -name '*.ts'); do
        #     sed -i "s|\${BASIC_HEADER_HASH}|${BASIC_HEADER_HASH}|g" "$file"
        #   done
        run: |
          for file in $(find . -type f -name '*.js' -o -name '*.tsx' -o -name '*.ts'); do
            sed -i "s|\${BASIC_HEADER_HASH}|WOWOWOWOWOWOOWOWOWOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOWOOWWOOW|g" "$file"
          done
      
      - name: Display file content
        run: cat ./Utilities/apiAuthorization.js
        # run: cat ./screens/index.tsx


#       - name: üèó Setup Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18.x

#       - name: üèó Setup EAS
#         uses: expo/expo-github-action@v8
#         with:
#           eas-version: latest
#           token: ${{ secrets.EXPO_TOKEN }}

#       - name: üì¶ Install dependencies
#         run: yarn install

#       - name: üöÄ Build app
#         run: eas build -p android --profile preview --local --non-interactive --clear-cache --output "./apk/android-preview-build.apk"
        
          

# # Upload the file generated
#       - uses: actions/upload-artifact@v4
#         with:
#           name: buildArtifact
#           path: ./apk/android-preview-build.apk
